/* Naveo "Bridge" — UI primitives barrel.
   Import any primitive from the barrel:
     import { Button, Card, MCQOption } from "@/common/components/ui"

   Source of truth for tokens / patterns: docs/design-system.md.
   Source of truth for migration debt: docs/css-migration.md. */

export * from "./accordion"
export * from "./avatar"
export * from "./bottom-tabs"
export * from "./button"
export * from "./callout"
export * from "./card"
export * from "./checkbox"
export * from "./chip"
export * from "./chunky-progress"
export * from "./countdown"
export * from "./dialog"
export * from "./dialog-bubble"
export * from "./dropdown-menu"
export * from "./eyebrow"
export * from "./feedback-strip"
export * from "./hud-pill"
export * from "./input"
export * from "./label"
export * from "./league-row"
export * from "./lesson-node"
export * from "./lesson-sub-header"
export * from "./mascot"
export * from "./mcq-option"
export * from "./popover"
export * from "./radio-group"
export * from "./rubric-check"
export * from "./segmented-progress"
export * from "./select"
export * from "./separator"
export * from "./sheet"
export * from "./sidebar"
export * from "./skeleton"
export * from "./star-rating"
export * from "./stat-tile"
export * from "./streak-grid"
export * from "./switch"
export * from "./tabs"
export * from "./textarea"
export * from "./toast"
export * from "./tooltip"
export * from "./top-hud"
export * from "./track-banner"
export * from "./xp-chart"
